parameters:
  excl: &excl |
    (?x)(
      (.*).svg
      (.*).png
    )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: *excl
      - id: end-of-file-fixer
        exclude: *excl
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        exclude: (.*pb2).py
        args: [--max-line-length=180]
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-lint
      - id: go-mod-tidy
