on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel
        goos: [linux]
        goarch: [arm64]
        source_path:
          - logger
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build example
        uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ldflags: -X github.com/ci4rail/velog/internal/version.Version=${{ github.event.release.tag_name }}
          build_flags: -tags netgo,osusergo,static_build
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.18.3.linux-amd64.tar.gz"
          project_path: "cmd/${{ matrix.source_path }}"
          binary_name: velog_${{ matrix.source_path }}
